import EStyleSheet from 'react-native-extended-stylesheet';
import { Fonts, Constants } from '../../Themes/';

export default EStyleSheet.create({
  $primary: '$primaryColor',
  $secondary: '$secondaryColor',
  $tertiary: '$tertiaryColor',
  container: {
    flex: 1,
  },
  logContainer: {
    flex: 1,
    padding: 15,
    marginTop: 20,
    borderWidth: 2,
    marginBottom: 5,
    borderRadius: 5,
    shadowOpacity: 0.8,
    marginHorizontal: 15,
    backgroundColor: '$bgColor',
    borderColor: '$primaryColor',
    shadowColor: 'rgba(0,0,0, 1)',
    shadowOffset: { height: 0, width: 0 },
  },
  logTextHeader: {
    fontSize: 16,
    marginBottom: 5,
    color: '#EDF0F1',
    alignSelf: 'center',
    fontFamily: 'Exo-Medium',
  },
  inputContainer: {
    flex: 1,
    margin: 5,
    padding: 15,
    elevation: 1,
    borderWidth: 2,
    borderRadius: 5,
    marginBottom: 85,
    shadowOpacity: 0.8,
    backgroundColor: '$bgColor',
    borderColor: '$primaryColor',
    shadowColor: 'rgba(0,0,0, 1)',
    shadowOffset: { height: 0, width: 0 },
  },
  inputHeader: {
    color: '$text',
    alignSelf: 'center',
    fontSize: Fonts.size.regular,
    fontFamily: Fonts.type.regular,
  },
  textInput: {
    margin: 5,
    padding: 3,
    fontSize: 14,
    color: '#EDF0F1',
    textAlign: 'center',
    borderBottomWidth: 1,
    fontFamily: 'Exo-Regular',
    borderColor: '$primaryColor',
  },
  logText: {
    color: '$text',
    alignSelf: 'center',
    fontSize: Fonts.size.regular,
    fontFamily: Fonts.type.regular,
  },
  logTextSets: {
    color: '$text',
    alignSelf: 'center',
    fontSize: Fonts.size.medium,
    fontFamily: Fonts.type.regular,
  },
  pastLogsContainer: {
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    elevation: 1,
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '$secondaryColor',
  },
  pastLogsFlatList: {
    width: Constants.DEV_WIDTH,
  },
  pastLogsHeader: {
    color: '$text',
    marginVertical: 30,
    fontSize: Fonts.size.h4,
    fontFamily: Fonts.type.bold,
  },
  pastLogsText: {
    color: '$text',
    alignSelf: 'center',
    fontSize: Fonts.size.h5,
    fontFamily: Fonts.type.medium,
  },
  exerciseListContainer: {
    top: 0,
    flex: 1,
    left: 0,
    right: 0,
    bottom: 0,
    elevation: 1,
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '$secondaryColor',
  },
  overlayButtonContainer: {
    width: 50,
    margin: 10,
    height: 50,
    elevation: 3,
    borderWidth: 2,
    shadowRadius: 2,
    borderRadius: 25,
    shadowOpacity: 0.8,
    shadowColor: '$primaryColor',
    borderColor: '$primaryColor',
    shadowOffset: { width: 0, height: 2 },
  },
  overlayIcon: {
    fontSize: 35,
    color: '$primaryColor',
  },
  exerciseListHeader: {
    marginTop: 40,
    color: '$text',
    marginBottom: 10,
    fontSize: Fonts.size.h4,
    fontFamily: Fonts.type.bold,
  },
  exerciseListButton: {
    padding: 20,
    width: Constants.DEV_WIDTH,
  },
  exerciseListText: {
    color: '$text',
    fontSize: Fonts.size.h5,
    fontFamily: Fonts.type.medium,
  },
});
